### PR TITLE
Readme corrections & improvements

### PR DESCRIPTION
**Pull request by parro-it**
I corrected examples in README to refer to array-first (I guess you copied them from array-last :smile: )
I also copied `Running tests` and `Contributing` from array-last, and link it in a related projects section.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
wow thanks! much appreciated. 

> I guess you copied them from array-last

guilty lol. I'm embarrassed that it has had that copy-pasta for this long, thanks for fixing it and thanks for taking the time to make it even better :)

**Comment by parro-it** [comment]
No worries, it happens! And thank to you for your work on little focused modules, they are really useful!

**Comment by jonschlinkert** [comment]
you're very welcome. I got hooked on small modules at the same time I got hooked on doing benchmarks and unit tests lol. turns out that modules like this one can be faster than native javascript (sometimes a lot faster), while being a little more flexible too.

thanks again!

**Comment by parro-it** [comment]
You're very welcome too! Other advantage or small modules  are that being very focused their source code could be easily understood by everyone, facilitating debugging,  improvement & contributions over time.
The only downside it's the time it took to discover good ones. I'm thinking of starting an awesome list of small modules to help improve this aspect.

**Comment by jonschlinkert** [comment]
> Other advantage or small modules are that being very focused their source code could be easily understood by everyone,

Indeed, I think that's the primary advantage. adding to what you said, microlibs are easier to unit test and easier to maintain in general. I have a number of microlibs with 100s of unit tests that (let's be honest) would have had just a few unit tests in larger library. which seems fine to most devs I guess, but it really opens your eyes much more to potential pitfalls when you move the code into a module.

> I'm thinking of starting an awesome list of small modules to help improve this aspect.

good idea! how about `awesome-microlibs`? 

on a similar note I've wanted to create a project to benchmark microlibs. that could be pretty fun too

**Comment by parro-it** [comment]
> good idea! how about awesome-microlibs?

Nice, I like the name! [Repo scaffolded here](https://github.com/parro-it/awesome-microlibs), feel free to contribute if you want.

> on a similar note I've wanted to create a project to benchmark microlibs. that could be pretty fun too

This would be really cool! I would like to use something like jsperf but that let me import npm modules, like tonicdev does... a sort of mix of the two

**Pull request merged**
